### ISSUE TITLE
Bot ignoring only say command

### ISSUE THREAD

**Issue by grundleface** [naschorr/hawking#54]
Sorry, new to Github.

Was working earlier today, then stopped responding to the \say command. Still responds to \help command. Wondering if this is an issue for my server or just something with the bot.

**Comment by naschorr** [comment]
Hey, no worries thanks for letting me know about anything that might be going wrong.

Is the issue still present? I've done a little playing around with it and can't seem to replicate it on my end. I'd still like to take a look at the logs and see if there was anything going wrong at that moment. Could you give me your Discord username, and roughly when you noticed the issue (and your timezone)? Here is fine, or you can DM me on Discord at Ranol#3716 if you'd like

**Comment by grundleface** [comment]
I sent you a request on Discord.

**Comment by naschorr** [comment]
I'm going through the backlog, and it seems like this is no longer relevant to the bot. Feel free to reopen if something changes.
